from typing import List
import numpy as np
import open3d as o3d
from drivence.utils import mesh_utils
from drivence.utils.format_convert import pc_numpy_2_pcd, pcd_2_pc_numpy
from drivence.module.data_gen.interface.occlusion.lidar_handler import LidarOcclusionHandler
class LidarComplexOcclusionHandler(LidarOcclusionHandler):
    def __init__(self, lidar_position = None): ...
    def set_vis(self, vis): ...
    def handle_occlusion_batch(self, pc_bg: np.ndarray, pc_obj: np.ndarray, mesh_obj_list: List[o3d.geometry.TriangleMesh], return_mask = False, labels_bg: np.ndarray = None, labels_obj: np.ndarray = None, intensity_bg: np.ndarray = None, instance_mask_obj: np.ndarray = None, return_bg_keep_mask = False): ...
    def get_occlusion_mask_batch(self, pc_bg: np.ndarray, pc_obj: np.ndarray, mesh_obj_list: List[o3d.geometry.TriangleMesh]): ...
    def get_occlusion_mask(self, mesh_obj: o3d.geometry.TriangleMesh, pc_bg: np.ndarray, pc_obj: np.ndarray): ...
    def handle_object_shadow(self, mesh_obj: o3d.geometry.TriangleMesh, pc_bg: np.ndarray, pc_obj: np.ndarray): ...
    def handle_center2obj_occlusion(self, mesh_obj: o3d.geometry.TriangleMesh, pc_bg: np.ndarray, pc_obj: np.ndarray): ...
    def get_inclusion_mask_by_mesh(self, pc_bg: np.ndarray, mesh: o3d.geometry.TriangleMesh) -> np.ndarray: ...
    def get_object_shadow_by_pcd(self, points: np.ndarray) -> o3d.geometry.TriangleMesh: ...
    def get_object_shadow_by_mesh(self, mesh_obj: o3d.geometry.TriangleMesh) -> o3d.geometry.TriangleMesh: ...
    def get_lidar2obj_pyramid_mesh(self, mesh_obj: o3d.geometry.TriangleMesh) -> o3d.geometry.TriangleMesh: ...
