import numpy as np
from typing import Optional
class SemanticLabelHandler:
    def __init__(self, dataset_type: str = None): ...
    def _get_vehicle_label_id_by_dataset(self, dataset_type: str) -> int: ...
    def set_dataset_type(self, dataset_type: str): ...
    def get_original_semantic_labels(self, dataset) -> Optional[np.ndarray]: ...
    def generate_vehicle_semantic_labels(self, vehicle_point_cloud: np.ndarray, instance_mask: Optional[np.ndarray] = None, semantic_labels: Optional[list] = None) -> Optional[np.ndarray]: ...
    def set_semantic_labels_to_output(self, dataset_output, semantic_labels: Optional[np.ndarray]): ...
def create_semantic_label_handler(dataset_type: str = None) -> SemanticLabelHandler: ...
