from drivence.module.data_gen.interface.occlusion.lidar_handler import LidarOcclusionHandler
from drivence.module.data_gen.interface.sensors.lidar import VirtualLidar
from typing import List
import numpy as np
import open3d as o3d
from drivence.utils.transform_utils import spherical_to_cartesian, cartesian_to_spherical
class Rays(object):
    def __init__(self, config: dict): ...
    def get_beam_index(self, phi: float): ...
    def get_vertical_angle(self, index: int): ...
    def get_vertical_angles(self, index_low, index_high): ...
    def find_vertical_angles(self, phi_low, phi_high): ...
    def get_horizontal_index(self, theta: float): ...
    def get_horizontal_angle(self, index: int): ...
    def get_horizontal_angles(self, index_low, index_high): ...
    def find_horizontal_angles(self, theta_low, theta_high): ...
    def _clip_phi(self, phi: float): ...
    def _clip_theta(self, theta: float): ...
    def get_points_in_spherical(self, theta_range, phi_range, r = None): ...
class RayCastingLidar(VirtualLidar):
    def __init__(self, lidar_config: dict, occlusion_handler: LidarOcclusionHandler): ...
    def simulate(self, ouput_dir, params: dict, obj_list: List[o3d.geometry.TriangleMesh]): ...
    def simulate_all(self, obj_list: List[o3d.geometry.TriangleMesh], return_rays = False, object_level = True, return_instance_mask = True): ...
    def init_casting_scene(self, obj_list: List[o3d.geometry.TriangleMesh]): ...
    def handle_occlusion(self, pc_bg: np.ndarray, pc_obj: np.ndarray, mesh_obj_list: List[o3d.geometry.TriangleMesh], return_mask = False, labels_bg: np.ndarray = None, labels_obj: np.ndarray = None, intensity_bg: np.ndarray = None, instance_mask_obj: np.ndarray = None, return_bg_keep_mask = False): ...
    def get_full_rays(self): ...
    def get_mesh_render_rays(self, mesh_obj: o3d.geometry.TriangleMesh): ...
    def get_meshes_render_rays(self, mesh_objs: List[o3d.geometry.TriangleMesh]): ...
    def cast_rays(self, scene, rays): ...
    def get_hit_points(self, rays, ray_cast_info: dict, obj_ids) -> List[np.ndarray]: ...
    def add_measurement_noise(self, pc_obj: List[List[float]]) -> np.ndarray: ...
