from drivence.dataset.common.label import Label
from drivence.utils.box_utils import Box3D
class BaseLabelGenerator(object):
    def __init__(self): ...
    def get_label_from_bounding_box3d(self, box3d: Box3D, calib_info, image_shape = None): ...
    def update_occlusion(self, labels: Label): ...
    def _update_occlusion_detail(self, labels: Label): ...
    def update_truncated(self, labels: Label): ...
    def _update_truncated_detailed(self, labels: Label): ...
    def get_objs_attr_from_labels(self, obj_list: list, has_image_box: bool = False): ...
import os
from natsort import natsorted
from drivence.entity.scene_info import SceneInfo
import numpy as np
def get_bounding_box(self, blender_outputs_dict: str, scene_info: SceneInfo) -> Label: ...
