from lidar_core.label_generator.base_label import BaseLabelGenerator
class LidarLabelGenerator(BaseLabelGenerator):
    def __init__(self): ...
    def generate_labels(self, labels, bounding_box_dicts, calib_info, lidar_scene_info): ...
