from lidar_core.label_generator.lidar_label import LidarLabelGenerator
class SemanticKITTILidarLabelGenerator(LidarLabelGenerator):
    def __init__(self): ...
    def generate_labels(self, labels, bounding_box_dicts, calib_info, lidar_scene_info): ...
