import numpy as np
def eq_15_up(Intensity_before, kd, theta, m, C_lambda, p_lambda, R, theta_s): ...
def eq_15_down(Intensity_before, theta, theta_s): ...
def eq_9(C_lambda, p_lambda, R): ...
def lambert_model(theta, kd, C_lambda, p_lambda, R): ...
def beckmann_model(theta, kt, m, C_lambda, p_lambda, R): ...
def lambert_beckmann_model(theta, kd, m, theta_T, C_lambda, p_lambda, R): ...
def eq_7(Pt_lambda_base, Dr, n_atm_lambda, n_sys_lambda, R, max_compensation_distance = 25.0): ...
def data(): ...
def data_car(): ...
def data_leaf(): ...
def data_ceramic(): ...
def data_marble(): ...
